# SPDX-FileCopyrightText: 2026 James Harton
#
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

permissions:
  contents: write
  security-events: write
  pages: write
  id-token: write

jobs:
  CI:
    uses: beam-bots/.github/.github/workflows/elixir-ci.yml@3f1f910d7d04bddf0f5dce2c55c32e47b6f5c550 # main
    with:
      enable-docs-deploy: true
      enable-release: true
    secrets:
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
